/*
  # Seed procedures data

  Insert initial procedures data into the database
*/

INSERT INTO procedures (id, name, description, full_description, institution_id, category, subcategory, duration, type, user_type, requirements, steps, is_digital, respaldo_legal, fecha_actualizado, fecha_revision) VALUES
('1', 'Renovación de DPI', 'Renovación del Documento Personal de Identificación vencido o próximo a vencer', 'Proceso para renovar tu Documento Personal de Identificación cuando esté vencido o próximo a vencer. Este trámite es esencial para mantener tu identificación oficial vigente.', 'renap', 'identidad', 'Documentos de identidad', '5-7 días hábiles', 'mixto', 'persona', ARRAY['DPI anterior (original y copia)', 'Partida de nacimiento certificada (no mayor a 6 meses)', 'Comprobante de residencia (no mayor a 3 meses)', 'Fotografías recientes tamaño cédula (2)'], ARRAY['Solicitud en línea o presencial', 'Presentar documentos requeridos', 'Toma de fotografía y huellas', 'Pago de aranceles', 'Esperar tiempo de procesamiento', 'Recoger documento en oficina asignada'], true, 'Decreto 90-2005 - Ley del Registro Nacional de las Personas', '2024-12-15', '2024-12-20'),

('2', 'Inscripción de Empresa', 'Registro e inscripción de nueva empresa en el Registro Mercantil', 'Proceso completo para inscribir una nueva empresa en el Registro Mercantil General de la República. Incluye todos los pasos necesarios para la constitución legal.', 'registro-mercantil', 'negocios', 'Registro empresarial', '10-15 días hábiles', 'presencial', 'empresa', ARRAY['Escritura pública de constitución', 'Testimonio de la escritura (3 copias)', 'Formulario de inscripción completo', 'Comprobante de pago de aranceles', 'Cédula del representante legal'], ARRAY['Elaboración de escritura pública', 'Presentación en ventanilla del Registro', 'Revisión de documentos', 'Calificación registral', 'Inscripción definitiva', 'Entrega de patente de comercio'], false, 'Código de Comercio - Decreto 2-70', '2024-11-20', '2024-12-18'),

('3', 'Licencia de Construcción', 'Solicitud de licencia municipal para construcción de vivienda', 'Obtención de licencia municipal para construcción, ampliación o remodelación de vivienda. Incluye revisión de planos y cumplimiento de normativas.', 'municipalidad-guatemala', 'vivienda', 'Permisos municipales', '20-30 días hábiles', 'presencial', 'persona', ARRAY['Planos arquitectónicos sellados', 'Planos estructurales', 'Escritura del terreno', 'Boleto de ornato vigente', 'Estudio de suelos', 'Formulario municipal completo'], ARRAY['Presentación de documentos', 'Revisión técnica municipal', 'Inspección del terreno', 'Aprobación de planos', 'Pago de licencia', 'Entrega de licencia aprobada'], false, 'Código Municipal - Decreto 12-2002', '2024-10-30', '2024-12-15'),

('4', 'Inscripción Universitaria', 'Proceso de inscripción para nuevo ingreso a universidad pública', 'Proceso completo de inscripción para estudiantes de nuevo ingreso en universidades públicas. Incluye asignación de curso básico y matrícula.', 'usac', 'educacion', 'Educación superior', '30-45 días', 'digital', 'persona', ARRAY['Título de diversificado', 'Certificado de notas de diversificado', 'Partida de nacimiento', 'DPI vigente', 'Fotografías tamaño cédula', 'Comprobante de pago de examen'], ARRAY['Pre-inscripción en línea', 'Pago de examen de admisión', 'Presentar examen', 'Consulta de resultados', 'Inscripción definitiva', 'Asignación de cursos'], true, 'Ley Orgánica de la Universidad de San Carlos - Decreto 325', '2024-12-01', '2024-12-22'),

('5', 'Certificado de Salud', 'Emisión de certificado médico para trámites laborales o académicos', 'Obtención de certificado de salud oficial requerido para trámites laborales, académicos o migratorios. Incluye exámenes médicos básicos.', 'mspas', 'salud', 'Certificaciones médicas', '3-5 días hábiles', 'presencial', 'persona', ARRAY['DPI vigente', 'Fotografía reciente', 'Comprobante de pago', 'Formulario de solicitud'], ARRAY['Solicitud en centro de salud', 'Examen médico general', 'Exámenes de laboratorio', 'Evaluación médica', 'Emisión de certificado', 'Entrega de documento'], false, 'Código de Salud - Decreto 90-97', '2024-11-15', '2024-12-19'),

('6', 'Antecedentes Penales', 'Solicitud de certificación de antecedentes penales', 'Certificación oficial de antecedentes penales requerida para trámites laborales, migratorios o académicos. Documento con validez legal.', 'organismo-judicial', 'justicia', 'Certificaciones judiciales', '2-3 días hábiles', 'digital', 'persona', ARRAY['DPI vigente', 'Formulario de solicitud', 'Comprobante de pago en línea', 'Correo electrónico válido'], ARRAY['Solicitud en línea', 'Pago electrónico', 'Verificación de identidad', 'Procesamiento de solicitud', 'Generación de certificado', 'Descarga del documento'], true, 'Ley del Organismo Judicial - Decreto 2-89', '2024-12-10', '2024-12-21');